project:
  type: website
  resources:
    - exercises.zip

website:
  page-navigation: true
  title: "Reproducible publishing with Quarto"
  description: "JSM 2024 - Reproducible publishing with Quarto"

  repo-url: https://github.com/mine-cetinkaya-rundel/quarto-jsm24
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#9bcbac"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/quarto-asa
        text: "GitHub organization"
      - icon: code-square
        href: https://posit.cloud
        text: "Posit Cloud"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - section: "Modules"
        contents:
          - href: 1-rmarkdown-quarto/index.qmd
            text: R Markdown to Quarto
          - href: 2-documents-slides/index.qmd
            text: Documents and slides
          - href: 3-websites-books/index.qmd
            text: Websites and books
          - href: 4-manuscripts/index.qmd
            text: Manuscripts

  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Mine Çetinkaya-Rundel + Charlotte Wickham"
    background: "#9bcbac" # Arylide Yellow

format:
  html:
    theme:
      light: [cosmo, style/quarto-asa.scss]
      dark: [cosmo, style/quarto-asa.scss, style/dark.scss]
    linkcolor: "#688773"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto
